name: some_widget_extensions
description: Collection of convenience extensions to be used on widgets. It conserves Flutter's API making it as familiar as possible.
version: 0.0.5
repository: https://github.com/sunderee/dart-published/tree/master/some_widget_extensions

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.13.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
