name: some_widget_extensions
description: Convenience extension methods to be used on widgets
version: 0.0.1
repository: https://github.com/sunderee/dart-published/tree/master/some_widget_extensions

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.13.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
