name: dart_scope_functions
description: Kotlin-inspired scope functions implemented in Dart with the goal of executing a block of code within the context of an object
version: 0.0.5
repository: https://github.com/sunderee/dart-scope-functions

environment:
  sdk: ">=2.19.6 <4.0.0"

dev_dependencies:
  lints: ^2.0.1
