name: nbr
description: Generic implementation of the network-bound-resource algorithm in Dart
version: 2.0.0
repository: https://github.com/sunderee/dart-published/tree/master/nbr

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.1.0
  mockito: ^5.4.1
  test: ^1.24.2
