name: nbr
description: Generic implementation of the network-bound-resource algorithm in Dart
version: 2.1.3
repository: https://github.com/sunderee/dart-published/tree/master/nbr

environment:
  sdk: ">=3.3.1 <4.0.0"

topics:
  - network-bound-resource
  - nbr
  - utility

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  mockito: ^5.4.4
