name: nbr
description: Generic implementation of the network-bound-resource algorithm in Dart
version: 2.0.3
repository: https://github.com/sunderee/dart-published/tree/master/nbr

environment:
  sdk: ">=3.1.0"

dependencies:
  meta: ^1.10.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.1.1
  mockito: ^5.4.2
  test: ^1.24.6
