name: nbr
description: Generic implementation of the network-bound-resource algorithm in Dart
version: 2.1.1
repository: https://github.com/sunderee/dart-published/tree/master/nbr

environment:
  sdk: ">=3.1.4 <4.0.0"

topics:
  - network-bound-resource
  - nbr
  - utility

dependencies:
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  mockito: ^5.4.2
