name: nbr
description: Generic implementation of the network-bound-resource algorithm in Dart
version: 0.0.4
repository: https://github.com/sunderee/nbr

environment:
  sdk: ">=2.19.6 <4.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
