name: nbr
description: Generic implementation of the network-bound-resource algorithm in Dart
version: 2.0.4
repository: https://github.com/sunderee/dart-published/tree/master/nbr

environment:
  sdk: ">=3.1.0 <4.0.0"

topics:
  - network-bound-resource
  - nbr
  - utility

dependencies:
  meta: ^1.10.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.1.1
  mockito: ^5.4.2
