name: nbr
description: Generic implementation of the network-bound-resource algorithm in Dart
version: 1.0.2
repository: https://github.com/sunderee/dart-published/tree/master/nbr

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
