name: nbr
description: Generic implementation of the network-bound-resource algorithm in Dart
version: 2.1.0
repository: https://github.com/sunderee/dart-published/tree/master/nbr

environment:
  sdk: ">=3.1.3 <4.0.0"

topics:
  - network-bound-resource
  - nbr
  - utility

dependencies:
  collection: ^1.17.2
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.1.1
  mockito: ^5.4.2
