name: dart_ms
description: Millisecond conversion utility library inspired by ms
version: 0.0.1
# repository: https://github.com/sunderee/dart-published/tree/master/dart_ms

environment:
  sdk: ">=3.0.0-417.4.beta"

dependencies:
  dart_scope_functions: ^0.0.6
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
