name: dart_ms
description: Millisecond conversion utility function inspired by ms (https://www.npmjs.com/package/ms)
version: 0.0.3
repository: https://github.com/sunderee/dart-published/tree/master/dart_ms

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_scope_functions: ^0.0.7
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
