name: dart_ms
description: Millisecond conversion utility function inspired by ms (https://www.npmjs.com/package/ms)
version: 0.0.5
repository: https://github.com/sunderee/dart-published/tree/master/dart_ms

environment:
  sdk: ">=3.1.0 <4.0.0"

topics:
  - ms
  - time

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
