name: dart_ms
description: Millisecond conversion utility function inspired by ms (https://www.npmjs.com/package/ms)
version: 0.0.7
repository: https://github.com/sunderee/dart-published/tree/master/dart_ms

environment:
  sdk: ">=3.1.4 <4.0.0"

topics:
  - ms
  - time

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.8
